# Generated by Django 4.0.2 on 2022-02-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_tag_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
